title: Felipe Mello
author:
  name: Felipe Mello
  email: mellofnd@gmail.com

show_excerpts: false

minima:
  date_format: "%b %-d, %Y"

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-redirect-from
